image: Visual Studio 2017 Preview
configuration: Release  
  
init:
  - git config --global core.autocrlf input

install:
  - cmd: curl -O https://download.microsoft.com/download/0/F/D/0FD852A4-7EA1-4E2A-983A-0484AC19B92C/dotnet-sdk-2.0.0-win-x64.exe
  - cmd: dotnet-sdk-2.0.0-win-x64.exe /install /quiet /norestart /log install.log 

skip_branch_with_pr: true
       
build_script:
  - cmd: dotnet restore Refit.sln 
  - cmd: dotnet build Refit\Refit.csproj -c Release 
  - cmd: dotnet pack Refit\Refit.csproj -c Release --no-build -o %APPVEYOR_BUILD_FOLDER%
  - cmd: dotnet test Refit.Tests\Refit.Tests.csproj -c Release 
  
artifacts:
  - path: '*.nupkg'
    name: Package

test: off

deploy:
  provider: NuGet
  server: https://www.myget.org/F/refit/api/v2/package
  symbol_server: https://www.myget.org/F/refit/symbols/api/v2/package
  on:
    branch: master  
  api_key:
    secure: bmqlJK8a5HYiUXOT99HXT1j7JiM5+fpR4kHhxIC30oaaEXbv94f0fKdiKlU1QC/l
  artifact: /.*\.nupkg/
