image: Visual Studio 2017
configuration: Release  
  
init:
  - git config --global core.autocrlf input

skip_branch_with_pr: true
       
before_build:
  - cmd: msbuild /t:restore Refit.sln
  
build:
  verbosity: normal
  parallel: true
  project: Refit.sln
  
after_build:  
  - cmd: msbuild Refit\Refit.csproj /t:pack /p:Configuration=Release /p:PackageOutputPath=%APPVEYOR_BUILD_FOLDER%
  
artifacts:
  - path: '*.nupkg'
  
deploy:
  provider: NuGet
  server: https://www.myget.org/F/refit/api/v2/package
  on:
    branch: master  
  api_key:
    secure: bmqlJK8a5HYiUXOT99HXT1j7JiM5+fpR4kHhxIC30oaaEXbv94f0fKdiKlU1QC/l
  artifact: /.*\.nupkg/
